//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public long C_Id { get; set; }
        public string PostedBy { get; set; }
        public string ImgURL { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<long> Likes { get; set; }
        public Nullable<long> Dislikes { get; set; }
    }
}
