//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLikeTag
    {
        public string UserId { get; set; }
        public int TagId { get; set; }
        public int Prefrence { get; set; }
    }
}
